v1:
    SIZE: 299
    LEARNING_RATE: 1e-5
    NUM_EPOCHS: 120
    MODEL: 'xception'
    BBOX_TYPE: 'RAW'

    BALANCE_CLASS_WEIGHT: 0    
    BALANCE_SAMPLES: 0
    DROPOUT_RATE: 0.6
    OUT_BINS: 2
    BATCH_SIZE: 32
    TRAIN_SUBSET: 1.0
    ENSEMBLE: 1
    WEIGHT_DECAY: 1e-6
    BALANCE_CLASSES: False
    FREEZE_BACKBONE: False

    train_augmentations:
        resize_and_pad: True
        random_rotation: 180
        horizontal_flip: True
        vertical_flip: True
        color_jitter: True                    
        color_jitter_params:
            brightness: 0.2
            contrast: 0.2
            saturation: 0.2
            hue: 0.1
        normalize: True
        normalize_mean: [0.5, 0.5, 0.5]       
        normalize_std: [0.5, 0.5, 0.5]

    val_augmentations:
        resize_and_pad: True
        normalize: True
        normalize_mean: [0.5, 0.5, 0.5]       
        normalize_std: [0.5, 0.5, 0.5]


v2:
    SIZE: 299
    LEARNING_RATE: 1e-5
    NUM_EPOCHS: 120
    MODEL: 'xception'
    BBOX_TYPE: 'BITMAP'

    BALANCE_CLASS_WEIGHT: 0   
    BALANCE_SAMPLES: 0
    DROPOUT_RATE: 0.6
    OUT_BINS: 2
    BATCH_SIZE: 32
    TRAIN_SUBSET: 1.0
    ENSEMBLE: 1
    WEIGHT_DECAY: 1e-6
    BALANCE_CLASSES: False
    FREEZE_BACKBONE: False

    train_augmentations:
        resize_and_pad: False
        random_rotation: 180
        horizontal_flip: True
        vertical_flip: True
        normalize: True
        normalize_mean: [0.5, 0.5, 0.5]       
        normalize_std: [0.5, 0.5, 0.5]

    val_augmentations:
        resize_and_pad: False
        normalize: True
        normalize_mean: [0.5, 0.5, 0.5]       
        normalize_std: [0.5, 0.5, 0.5]